### ISSUE TITLE
[Feature Request] Filter system

### ISSUE THREAD

**Issue by florianlefeuvre** [kevinpainchaud/reowl#1]
Hi Kevin,

**First of all, thanks for this project !**

Anticipating a growing list of replays, do you plan to add a filter system ?

Filtering game cards elements by team could be interesting if anyone wants to see all the game from only X or Y team (by **_filtering out the other cards_**, or maybe by **_dimming/re-ordering them_** ? dunno).

Cheers :)

**Comment by kevinpainchaud** [comment]
Hi Florian,

Thanks you very much for your feedback!

Yes, this is a great idea that several people have already suggested to me.
I plan to add this filter system (with calendar of matches per week) in the coming weeks.

Thanks again, and feel free to suggest PR if you want to participate in the project.
